name: ngs_env

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - fastqc=0.12.1
  - trimmomatic=0.39
  - sra-tools=3.0.10
  - hisat2=2.2.1
  - subread=2.0.6
  - bioconductor-deseq2=1.40.2
